# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                      MYMC LITE                                               | #
# |                                                                                              | #
# |                Light-weight plugin for basic server setup (including hubs)                   | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #
# Author: supposedly_sam

# Join/Leave messages
# Supports PlaceholderAPI and minecraft color codes
# Leave blank to use vanilla join/leave messages
join-message: "&f[&a+&f] &7%player_name%"
leave-message: "&f[&c-&f] &7%player_name%"

# Force players to spawn on joining
# If spawn not set, world spawn is used
spawn:
  # Force teleport player to spawn on join
  # If spawn not set, world spawn is used
  force-spawn-on-join: true
  # Enable/Disable '/spawn' command
  command-enabled: true
  # Send player to another server on execution of '/spawn'
  # Empty string will send the player to spawn location or world spawn
  send-to-server: ""

# Enable or disable build/interact in the server
build:
  # Changing this to false, disables build/interact in the server
  # /build cmd can be used to bypass this
  enabled: true

# Chat Format
# Enabling chat will allow MymcLite to handle player chat
chat:
  enabled: true
  # Default chat format
  # Supports PlaceholderAPI and minecraft color codes
  # In-built placeholders:
  # - %author%: Message author
  # - %message%: Message content
  chat-format: "&8&l[&r&f%author%&8&l]&r &7%message%"

# Disabled commands
# List commands to restrict players from accessing them
# Players with 'mymclite.disabled-commands.bypass' permission
# can bypass this check
disabled-commands:
  commands:
    - "pl"
    - "plugins"
    - "ver"
    - "version"
    - "?"
    - "help"
  disable-message: "&cThis command has been disabled."

# Game Selector Inventory
# Enable/Disable a game selector menu (Mainly used for hubs)
game-selector:
  enabled: false

  # Hotbar item which will execute the /gsel command
  # Given to players on join
  # Disabling this will require players to use /gsel command manually
  hotbar-item:
    enabled: true
    # Player's hotbar slot in which this item is placed
    # Between 0 and 8
    hotbar-slot: 0
    # Material of the hotbar item
    # Spaces must be replaced with '_'
    material: "SUNFLOWER"
    # Display name of the item
    # Supports PlaceholderAPI and minecraft color codes
    display-name: "&3Game Selector"

  # Title of the game selector inventory
  # Supports PlaceholderAPI and minecraft color codes
  title: "&3Game Selector"
  # Size of the inventory
  # Must be multiples of 9 (9, 18, 27, 36, 45)
  # Inventory slot is 0 based (counted from 0 to 45)
  size: 27
  # If enabled, all slots (other than which contains items)
  # will be occupied with a filler glass
  filler-glass-enabled: true
  # Items sections
  # To add more items, copy the below configuration
  items:
    # Item key (Must be unique)
    item1:
      # Material to be shown in the inventory
      # Spaces must be replaced with '_'
      material: "GRASS_BLOCK"
      # Amount of items to be shown
      # Between 1 and 64
      count: 1
      # If the item should be shown as enchanted
      # Enchantment will be hidden (on hover)
      enchanted: true
      # Display name of the item
      # Supports PlaceholderAPI and minecraft color codes
      display-name: "Sample"
      # Lore or text shown on hover of the item
      # Support PlaceholderAPI and minecraft color codes
      lore:
        - "&aLine 1"
        - "Line 2"
      # Position in the inventory where this item should be placed
      # Between 0 to (size-1)
      # If multiple items have the same position (it will be overwritten)
      inventory-position: 0
      # Commands to be executed by the player on click of the item
      # Leaving this empty will remove click commands from this item
      # Available click types 'LEFT', 'RIGHT', 'SHIFT_LEFT', 'SHIFT_RIGHT', 'DROP' (Q)
      # Format: CLICK_TYPE: "command"
      # Click types must be uppercase, commands do not need '/'
      click-commands:
        LEFT: "list"
        RIGHT: "pl"

    item2:
      material: "CHEST"
      count: 1
      enchanted: true
      display-name: "Sample"
      lore:
        - "&aLine 1"
        - "Line 2"
      inventory-position: 1
      click-commands:
        LEFT: "list"
        RIGHT: "pl"