name: MymcLite
version: '1.0-SNAPSHOT'
main: me.supposedly_sam.mymcLite.MymcLite
api-version: '${api.version}'
commands:
  mlreload:
    description: Reloads the config.yml
    usage: /<command>
  setspawn:
    description: Set spawn location of the world
    usage: /<command>
  spawn:
    description: Teleport to spawn
    usage: /<command> [player]
    aliases:
      - l
      - lobby
      - hub
  build:
    description: Toggle build mode if build is disabled
    usage: /<command> [player]
    aliases:
      - b
  goto:
    description: Transfer between servers in a bungeecord network
    usage: /<command> <server> [player]
  gameselector:
    description: Display the game selector gui
    usage: /<command> [player]
    aliases:
      - gsel
      - menu
      - game

permissions:
  mycmlite.reload:
    default: op
    description: Permission to reload the plugin config
  mymclite.setspawn:
    default: op
    description: Permission to set spawn
  mymclite.spawn.others:
    default: op
    description: Permission to teleport other players to spawn
  mymclite.build:
    default: op
    description: Permission to toggle build mode
  mymclite.goto.others:
    default: op
    description: Permission to send other players to another server
  mymclite.chat.colours:
    default: op
    description: Permission to use chat colours
  mymclite.disabled-commands.bypass:
    default: op
    description: Permission to bypass disabled commands
  mymclite.gselector.others:
    default: op
    description: Permission to show game selector to other players