# Force players to spawn on joining
# Requires set spawn to work
spawn:
  # Force teleport player to spawn on join
  force-spawn-on-join: true
  # Enable/Disable '/spawn' command
  command-enabled: true

# Enable or disable build/interact in the server
build:
  # Changing this to false, disables build/interact in the server
  # /build cmd can be used to bypass this
  enabled: true

# Chat Format
# Enabling chat will allow MymcLite to handle player chat
chat:
  enabled: true
  # Default chat format
  # PlaceholderAPI and minecraft color codes supported
  # In-built placeholders:
  # - %author%: Message author
  # - %message%: Message content
  chat-format: "&8&l[&r&f%author%&8&l]&r &7%message%"

# Disabled commands
# List commands to restrict players from accessing them
# Players with 'mymclite.disabled-commands.bypass' permission
# can bypass this check
disabled-commands:
  commands:
    - "pl"
    - "plugins"
    - "ver"
    - "version"
    - "?"
    - "help"
  disable-message: "&cThis command has been disabled."

# Game Selector Inventory
game-selector:
  enabled: true
  title: "&3Game Selector"
  size: 27
  filler-glass-enabled: true
  items:
    item1:
      material: "GRASS_BLOCK"
      count: 1
      enchanted: true
      display-name: "Sample"
      lore:
        - "Line 1"
        - "Line 2"
      inventory-position: 3